apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: order-store-fe-store-demo-project
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: order-store-fe-store-demo-project
    app.kubernetes.io/part-of: store-demo-project
  name: order-store-fe-store-demo-project
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: order-store-fe-store-demo-project
status:
  loadBalancer: {}
